### ISSUE TITLE
CLI session ended when trying to send an erc20 or erc721

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-cli#289]
**Describe the bug**
The cli session is suddenly closed for me when trying to send an erc20 or a erc721 to a different safe.

**To Reproduce**
On goerli, from a safe + loaded cli owner try to send either of them via the proposed tx structure of:

`<address> <token_address> <amount/int> --safe-nonce <int>`

**Expected behavior**
Transaction going through.

**Obtained result**
```
blockchain > 0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C > send_erc721 0xaA71DB6cFDa182C0C19738736caF8eb37e0ED6B1 0x5B9aE6234Cf1E447680c245200E066091E631Bf3 1 --safe-nonce 220
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/safe-cli", line 33, in <module>
    sys.exit(load_entry_point('safe-cli==0.7.1', 'console_scripts', 'safe-cli')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/safe_cli/main.py", line 144, in main
    safe_cli.loop()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/safe_cli/main.py", line 112, in loop
    self.prompt_parser.process_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 136, in process_command
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 38, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 219, in send_erc721
    args.to, args.token_address, args.token_id, safe_nonce=args.safe_nonce
AttributeError: 'Namespace' object has no attribute 'token_id'
```

**Additional context**
Issue was reproducible via the default and tx-service modes and also regardless of the safe threshold (tried 1/X and 2/X).

**Comment by moisses89** [comment]
@JagoFigueroa the screenshot is cutting the last lines, could you share the complete traceback error in text?

**Comment by Uxio0** [comment]
@JagoFigueroa could you retest again with last `main` version?

**Comment by JagoFigueroa** [comment]
Tested and verified with the latest changes! 🚀
