### ISSUE TITLE
Does this tool support chains without 1559 transaction (only 155)

### ISSUE THREAD

**Issue by Pana** [safe-global/safe-cli#340]
# What is needed?
Want to use this tool on chains that are compatible but do not support 1559 tranaction

# Background
Some EVM-compatible chains do not support 1559 transaction

**Comment by Uxio0** [comment]
It should work, did you have any problem?

**Comment by Pana** [comment]
When I run it on the EVM chain only supports 155 tx, it failed

**Comment by Uxio0** [comment]
Can you share the output of the CLI?

**Comment by ilzheev** [comment]
Can you re-open this? @Uxio0 
v1.3.0

```bash
Safe will be deployed on 0xA327cc41971f532c6be8EdB51692f5522B16Ae7a, looks good? [y/N]: y
/Users/anton/miniconda3/lib/python3.9/site-packages/web3/eth/eth.py:186: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/eth/eth.py", line 184, in max_priority_fee
    return self._max_priority_fee()
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 325, in request_blocking
    return self.formatted_response(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 278, in formatted_response
    raise MethodUnavailable(error)
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'Method not found'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/miniconda3/bin/safe-creator", line 8, in <module>
    sys.exit(main())
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/safe_cli/safe_creator.py", line 220, in main
    ethereum_tx_sent = proxy_factory.deploy_proxy_contract_with_nonce(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/gnosis/safe/proxy_factory.py", line 253, in deploy_proxy_contract_with_nonce
    return self._deploy_proxy_contract(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/gnosis/safe/proxy_factory.py", line 149, in _deploy_proxy_contract
    tx = deploy_fn.build_transaction(tx_params)
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/contract/contract.py", line 354, in build_transaction
    return build_transaction_for_function(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/contract/utils.py", line 232, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(w3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 263, in cytoolz.functoolz.curry.__call__
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/_utils/transactions.py", line 132, in fill_transaction_defaults
    default_val = default_getter(w3, transaction)
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/_utils/transactions.py", line 75, in <lambda>
    lambda w3, tx: w3.eth.max_priority_fee
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/eth/eth.py", line 190, in max_priority_fee
    return fee_history_priority_fee(self)
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/_utils/fee_utils.py", line 46, in fee_history_priority_fee
    fee_history = eth.fee_history(*PRIORITY_FEE_HISTORY_PARAMS)  # type: ignore
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/eth/eth.py", line 228, in fee_history
    return self._fee_history(block_count, newest_block, reward_percentiles)
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 325, in request_blocking
    return self.formatted_response(
  File "/Users/anton/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 278, in formatted_response
    raise MethodUnavailable(error)
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'Method not found'}
```
