### ISSUE TITLE
Not possible to execute tx with ledger HW on blockchain mode

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-cli#362]
**Describe the bug**
I am having some trouble executing transactions with Ledger while on blockchain mode.

**To Reproduce**
On a threshold 1 safe, load ledger owner and try so send any type of transaction

(I was able to reproduce the issue in Gnosis Chain & Sepolia)

**Expected behavior**
Transaction executed successfully

**Current behaviour**
safe-cli crashes with the following error:
```
Do you want to execute tx SafeTx - safe=0x0A64A32c010aa70fe79Ac32acAeFF0B3a7EE76b3 - to=0x0A64A32c010aa70fe79Ac32acAeFF0B3a7EE76b3 - value=1 - data= - operation=0 - safe-tx-gas=0 - base-gas=0 - gas-price=0 - gas-token=0x0000000000000000000000000000000000000000 - refund-receiver=0x0000000000000000000000000000000000000000 - signers = ['0x72d315603Ba7eE9C100f4207a80248F58381A20d'] [y/N]: y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/safe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File ".../safe_cli/main.py", line 156, in main
    safe_cli.loop()
  File ".../safe-cli/safe_cli/main.py", line 113, in loop
    self.prompt_parser.process_command(command)
  File ".../safe-cli/safe_cli/prompt_parser.py", line 148, in process_command
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/prompt_parser.py", line 42, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/prompt_parser.py", line 232, in send_ether
    safe_operator.send_ether(args.to, args.value, safe_nonce=args.safe_nonce)
  File ".../safe-cli/safe_cli/operators/safe_operator.py", line 542, in send_ether
    return self.send_custom(to, value, b"", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/operators/safe_operator.py", line 537, in send_custom
    return self.prepare_and_execute_safe_transaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/operators/safe_operator.py", line 911, in prepare_and_execute_safe_transaction
    return self.execute_safe_transaction(safe_tx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/operators/safe_operator.py", line 127, in decorated
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/operators/safe_operator.py", line 927, in execute_safe_transaction
    tx_hash, tx = self.hw_wallet_manager.execute_safe_tx(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../safe-cli/safe_cli/operators/hw_wallets/hw_wallet_manager.py", line 201, in execute_safe_tx
    safe_tx.tx_hash = safe_tx.ethereum_client.w3.eth.send_raw_transaction(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/web3/eth/eth.py", line 373, in send_raw_transaction
    return self._send_raw_transaction(transaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/web3/manager.py", line 325, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/web3/manager.py", line 288, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
```

**Comment by fafrd** [comment]
Same issue. Tried with several RPCs:
- Alchemy API failed with `ValueError: {'code': -32000, 'message': 'transaction underpriced'}`
- Quicknode API resulted in a tx with a 0.1 gwei gas price, had to replace tx
- `https://eth.llamarpc.com` resulted in a very low gas price, never reached public mempool
- `https://rpc.ankr.com/eth` failed with `ValueError: {'code': -32000, 'message': 'failed with 6766234 gas: max fee per gas less than block base fee: address [OMITTED], maxFeePerGas: 47941127594, baseFee: 50419595365'}`
- Personal local Geth node failed with `ValueError: {'code': -32000, 'message': 'fee cap less than block base fee: address [OMITTED], gasFeeCap: 44593875450 baseFee: 45784370040'}`

**Comment by fafrd** [comment]
Hey @moisses89, any update?

**Comment by moisses89** [comment]
Hey @fafrd I couldn´t take a look for now, it looks like is an issue with the gas price estimation when the transaction is executed with ledger.  
> I just tried and I couldn't reproduce, could you try to change the RPC provider?

It works for me the first time, because leave a transaction in the mempool, then if I try to execute other transaction the issues mentioned appear. 
I'll try to fix it.

**Comment by JagoFigueroa** [comment]
Tested and verified, I am now able to execute transactions on a ledger while on blockchain mode 😄

**Comment by fafrd** [comment]
@moisses89 @Uxio0 Would you please cut a new release incorporating this fix?

My company is developing an emergency response runbook, it would be much easier for us to simply ask responders to 'pip install' instead of pulling down this repo and building.

**Comment by Uxio0** [comment]
Makes sense @fafrd , will do today

**Comment by Uxio0** [comment]
Done https://github.com/safe-global/safe-cli/releases/tag/v1.1.0
